import { Restaurant } from './restaurant';

export const RESTAURANTS: Restaurant[] = [
  { id:11, name: 'Restaurant 1',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id:12, name: 'Restaurant 2',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id: 13, name: 'Restaurant 3',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id: 14, name: 'Restaurant 4',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id: 15, name: 'Restaurant 5',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id: 16, name: 'Restaurant 6',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id: 17, name: 'Restaurant 7',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id: 18, name: 'Restaurant 8',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id: 19, name: 'Restaurant 9',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' },
  { id: 20, name: 'Restaurant 10',desc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sagittis, diam quis suscipit convallis, nunc ex varius tortor, id gravida quam nibh quis est. Proin tempor mattis consequat. ',location:'Akshya Nagar 1st Block 1st Cross, Rammurthy nagar, Bangalore-560016' }
];
